### ISSUE TITLE
isNavigation does not make thumbnail a navigation link

### ISSUE THREAD

**Issue by AndyTruffs** [Splidejs/vue-splide#10]
Hi

I've got vue-splide working beautifully (great package) with a primary and secondary thumbnail slider.  The primary and secondary are sync'd and working fine together, but there's one issue I don't understand how to resolve.

Secondary has isNavigation: true, which I can see adds some CSS properties to the thumbnail slider, but the thumbnails themselves do not become navigation links.  Cursor on mouse hover remains as the default and clicking the thumbnail has no effect.

Comparing the `<li>` elements on my secondary to the example on splidejs.com shows that role="button" and aria-label="Go to slide X" are missing from mine.

Is this a bug, or is it possible I've used two incompatible options?

Thanks

```
splidePrimary: {
	type       : 'loop',
	heightRatio: 0.6,
	pagination : false,
	arrows     : true,
	cover      : true,
	speed      : 300,
	lazyLoad   : 'nearby',
	preloadPages : 1,
	classes: {
	  arrow : 'splide__arrow splide-custom-arrow',
	},
},
splideSecondary: {
	type         : 'slide',
	rewind       : true,
	fixedWidth   : 130,
	fixedHeight  : 70,
	isNavigation : true,
	gap          : 0,
	focus        : 'center',
	pagination   : false,
	cover        : true,
	arrows       : false,
	lazyLoad     : 'nearby',
	preloadPages : 4,
	breakpoints : {
	    '600': {
		fixedWidth  : 66,
		fixedHeight : 40,
	    }
	}
}
```

**Comment by NaotoshiFujita** [comment]
Close the issue due to the major version update.
Feel free to create a [new issue](https://github.com/Splidejs/splide/issues) or open a [new discussion](https://github.com/Splidejs/splide/discussions).
