### ISSUE TITLE
How to go to particular slide into Thumbnail Slider ?

### ISSUE THREAD

**Issue by KiranBolaniya** [Splidejs/vue-splide#12]
I have tried using go but it's not working because of the sync method.
For the secondary slider, it selects the particular slide but for primary it doesn't work or say sync.

**Comment by laraketai** [comment]
same issue

**Comment by dev-kopernik-info** [comment]
Use some timeout in mount function.

Something like this
`setTimeout(() => { 
     this.$refs.primary.sync(this.$refs.secondary.splide)
  }, 500)`

**Comment by NaotoshiFujita** [comment]
Close the issue due to the major version update.
Feel free to create a [new issue](https://github.com/Splidejs/splide/issues) or open a [new discussion](https://github.com/Splidejs/splide/discussions).
