### ISSUE TITLE
SSR suport

### ISSUE THREAD

**Issue by k-ivan** [Splidejs/vue-splide#15]
Hi @NaotoshiFujita 

I would like to have the markup already on the server. Is it possible to add support SSR support?
It may be possible to wrap the splidejs plugin in a UMD wrapper.
![Screenshot 2020-11-06 183633](https://user-images.githubusercontent.com/6150895/98384860-57aefd80-205f-11eb-9a89-541d206e4ec8.jpg)

**Comment by k-ivan** [comment]
Sorry, I was in a hurry with the issue.
I was confused by nuxtjs behavior, after restarting the client mode flag was triggered.

**Comment by k-ivan** [comment]
And yet, I decided to reopen this issue
I came to the conclusion that I could use the plugin only in client mode(include markup). But as I wrote above, I would like to have the slider markup on the server, an attempt to use vanilla splide will result in an error on SSR.

**Comment by NaotoshiFujita** [comment]
In Next.js(not Nuxt.js), there is a way to disable SSR for a specific component(see #95).
Is there not a way to do that in Nuxt.js?

**Comment by k-ivan** [comment]
Quite right. In Nuxt.js it is also possible, but unfortunately, then the component markup will not exist on the server. That is, page jumps are possible at the time of initialization on the client.
Maybe I'm getting too hung up on this little thing)

**Comment by NaotoshiFujita** [comment]
I see. I should support SSR in the future, but it will not be soon...

**Comment by k-ivan** [comment]
Thanks! Will wait. So far I decided through `require`.

It seems like a wrapper(instead of `window.Splide`) should help
```js
// webpack
output: {
  filename: 'splide.js',
  library: 'Splide',
  libraryTarget: 'umd',
  libraryExport: 'default',
  umdNamedDefine: true,
  globalObject: `(typeof self !== 'undefined' ? self : this)`
}
```

**Comment by pfzwaan** [comment]
(node:24412) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension., import VueSplide from '@splidejs/vue-splide'; 
createServer((page) =>
    createInertiaApp({
        page,
        render: renderToString,
        title: (title) => `${title} - ${appName}`,
        resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
        setup({ App, props, plugin }) {
            const app = createSSRApp({ render: () => h(App, props) })
            .use(plugin)
            .use(VueSplide)
            .use(ZiggyVue, {
                ...page.props.ziggy,
                location: new URL(page.props.ziggy.location),
            })

Anyone knows how to solve this?
