### ISSUE TITLE
All slides visible with perPage: 1

### ISSUE THREAD

**Issue by alexcroox** [Splidejs/vue-splide#2]
I have the following configs:

```
galleryOptionsMain: {
        rewind: true,
        perPage: 1,
        perMove: 1,
        heightRatio: 0.66,
        pagination: false,
        arrows: false
},

galleryOptionsThumbnails: {
        rewind: true,
        gap: '1rem',
        pagination: false,
        arrows: false,
        fixedWidth: 110,
        fixedHeight: 70,
        cover: true,
        focus: 'center',
        isNavigation: true,
        updateOnMove: true
},
```

However my gallery slides seem to all have the class 'is-visible' applied to them, making them vertically stack. I'm using my own css but using the splide min css and can see Splide has correctly set a fixed width/height inline style on each.

![image](https://user-images.githubusercontent.com/1065835/85222401-9430d400-b3b2-11ea-9138-982a9d69560d.png)

**Comment by Splidejs** [comment]
Did you update CSS too?

**Comment by alexcroox** [comment]
Ah no I didn't thank you, working now https://github.com/Splidejs/vue-splide/issues/1
