### ISSUE TITLE
new slides does not show in dynamic created slides

### ISSUE THREAD

**Issue by hjelmdal** [Splidejs/vue-splide#22]
Hi, 

do I need to do anything to re-init the slider upon creation of a new slide? My code looks like:

<splide :options="options">
            <splide-slide v-for="round in rounds" v-bind:key="'roundnum' + round.id">...</splide-slide>
</splide>

Upon creation of a new "round" I can see in my VueDevtools that a new SplideSlide is correctly added, and I can see that it is there (just outside the viewport) but it seems that the slider thinks that the previous last item is still the last one.

Any suggestions or is this a bug? 
Thanks alot!

**Comment by hjelmdal** [comment]
My god.... what a stupid mistake... forgot to attach the :slides to the main component... SORRY!

**Comment by hjelmdal** [comment]
Is it possible though to navigate to the end of the slider upon creation of a new slide?

**Comment by solamichealolawale** [comment]
You can try and use the API

**Comment by hjelmdal** [comment]
thanks for the reply. How do I access the splide api  on a given slider within a component using the <splide> component?

**Comment by solamichealolawale** [comment]
To access the API, you'll have to use refs.
I guess one needs to update their documentation, that was what led me here.

[See more here - https://github.com/Splidejs/vue-splide/issues/20 ](https://github.com/Splidejs/vue-splide/issues/20)
