### ISSUE TITLE
Internet Explorer 11 support

### ISSUE THREAD

**Issue by alexcroox** [Splidejs/vue-splide#3]
Just an FYI, the vue component isn't IE 11 compatible, I had to transpile this library before it would work;

(in Vue)

![image](https://user-images.githubusercontent.com/1065835/86098222-ba8af980-baad-11ea-93e2-45c3301c0e99.png)

![image](https://user-images.githubusercontent.com/1065835/86099099-ec509000-baae-11ea-8753-b43624198653.png)

![image](https://user-images.githubusercontent.com/1065835/86099119-f5416180-baae-11ea-842e-4e56d03addd9.png)

**Comment by NaotoshiFujita** [comment]
Thank you for your info 😄 

Yes, this Vue library needs to be transpiled.
