### ISSUE TITLE
Typescript declaration problem

### ISSUE THREAD

**Issue by frankykubo** [Splidejs/vue-splide#56]
### Version

0.5.1

### Description

I updated from older version (0.3.5) to the newest with Splide v3 in my Vue 3 - TypeScript project. Whenever I try to compile, I got implicitAny error:

> ERROR in node_modules/@splidejs/vue-splide/src/js/components/index.ts:2:40
TS7016: Could not find a declaration file for module './SplideSlide/SplideSlide.vue'. 'project_root/node_modules/@splidejs/vue-splide/src/js/components/SplideSlide/SplideSlide.vue.js' implicitly has an 'any' type.
    1 | export { default as Splide } from './Splide/Splide.vue';
  > 2 | export { default as SplideSlide } from './SplideSlide/SplideSlide.vue';`

In older version, I've had almost the same problem, but I was able to fix it by creating .d.ts file containing
`declare module '@splidejs/vue-splide';`

In this case, this does not work. Thanks for help.

### Steps to Reproduce

1. Create Vue 3 Typescript project
2. Install @splidejs/vue-splide
3. Setup component containing Splide and SplideSlide

### Expected Behaviour

Without TypeError.

**Comment by NaotoshiFujita** [comment]
What happens if you import your own single file component (.vue)?
Can your compiler recognize yours?

**Comment by frankykubo** [comment]
What I tried was create d.ts file containing:
> 
> `declare module '*SplideSlide.vue' { import { DefineComponent } from 'vue'; // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/ban-types const component: DefineComponent<{}, {}, any>; export default component; }`

This fixed the issue for me, after all I found out, that since I was using my own css, I missed this lines:

`.splide.is-initialized, .splide.is-rendered {
  visibility: visible
}`
so I clearly could not see anything. Thank you. Well that lead me to another issue, I'll create new topic for that.
