### ISSUE TITLE
Grid Extension

### ISSUE THREAD

**Issue by CoolS2** [Splidejs/vue-splide#6]
There is no way to use grid extension

**Comment by NaotoshiFujita** [comment]
That is a good point! Now the component accepts `extensions` prop in v0.3.3.

Here is an [example code](https://github.com/Splidejs/vue-splide/blob/master/examples/src/js/examples/components/VideoExample.vue) for Video extension. The Grid extension doesn't have CSS though.

**Comment by CoolS2** [comment]
Thanks, Work like a charm
