### ISSUE TITLE
stylizing with scoped style

### ISSUE THREAD

**Issue by maico910** [Splidejs/vue-splide#60]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Vue Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.5.14

### Description

It's not possible to stylizing with scoped style, by some reason, it's not adding vue `data-v` attribute, it's not using in Vue.js? 

![image](https://user-images.githubusercontent.com/24510745/144729603-db41d76d-f9ee-40ed-a148-59b3ce83bcc2.png)

### Steps to Reproduce

1. add some code into scoped style, like:

```js
<style scoped>
.splide__arrows {
  background: black;
}
</style>
```

### Expected Behaviour

Apply the style into component

**Comment by NaotoshiFujita** [comment]
It's not possible because arrows are generated by the native function.
Use the `:deep` selector or manually provide arrows by a slot.

**Comment by maico910** [comment]
Ok, I understood.

It's make sense to rewrite the splide into Vue.is? Not only by this reason, make more easier to add splide's default components, I have a lot of difficult to do this

**Comment by NaotoshiFujita** [comment]
I'm not planning to do that for now because there are already other carousel libraries made for Vue.
