### ISSUE TITLE
vue warn with nuxt 3 on preview

### ISSUE THREAD

**Issue by zynth17** [Splidejs/vue-splide#61]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Vue Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.5.18

### Description

![image](https://user-images.githubusercontent.com/45350572/156127274-e0b43208-d420-4f6d-9e9e-fe8c7e1abe05.png)

got a weird error on previewing nuxt 3 after the build
it does work and run on developent. but got the warning on preview mode

### Reproduction Link

https://github.com/zynth17/vue-splide-nuxt3-bug

### Steps to Reproduce

1. install nuxt 3
2. install splide
3. use it on a page
4. run npm run build
5. run npm start 
6. open the preview and see warning
...

### Expected Behaviour

supposed to not have any warning

**Comment by NaotoshiFujita** [comment]
You seem to be referencing 2 different Vue instances. Make sure to use the same instance in a way that matches your project environment, such as deduping, hoisting, etc.
I can do nothing on the library side since this is not a Splide issue.

**Comment by zynth17** [comment]
> You seem to be referencing 2 different Vue instances. Make sure to use the same instance in a way that matches your project environment, such as deduping, hoisting, etc.
> 
> I can do nothing on the library side since this is not a Splide issue.
> 
> 

ah i see so this is on the nuxt side. thankyou!
