### ISSUE TITLE
 Dynamically changing options does not work

### ISSUE THREAD

**Issue by ThomasTraineau** [Splidejs/vue-splide#62]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Vue Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.5.18

### Description

I am trying to change splide's width dynamically to make the carousel fullscreen when the user clicks on it. So I set : 
```
:options="carouselFullscreen ? bigCarouselOptions : smallCarouselOptions"
```
The options are indeed different (I can see them changing in vue dev tools) but they do not take effect. I think it is due to the fact that a style attribute is set and stays at the first value, but if I change this as well dynamically, the slides of the carousel are a bit offset when changing the width.

### Steps to Reproduce

```
 <Splide
      :class="
        carouselFullscreen
          ? 'splide small-carousel is-initialized splide--slide splide--ltr splide--draggable is-active'
          : 'splide small-carousel is-initialized splide--slide splide--ltr splide--draggable is-active'
      "
      :style="carouselFullscreen ? 'max-width: 100vw;' : 'max-width: 95vw;'"
      @click="carouselFullscreen = !carouselFullscreen"
      :options="carouselFullscreen ? bigCarouselOptions : smallCarouselOptions"
    >
      <SplideSlide
        v-for="picture in pictures"
        :key="picture.id"
        v-show="!arePicturesLoading"
      >
        <img
          :class="carouselFullscreen ? 'fullscreen-picture' : 'small-picture'"
          :onload="pictureLoaded"
          :src="picture.name"
        />
      </SplideSlide>
    </Splide>



smallCarouselOptions: {
        gap: "1rem",
        arrows: false,
        width: "95vw",
      },
bigCarouselOptions: {
        gap: "1rem",
        arrows: false,
        width: "100vw",
      },
```

A workaround I found was to create 2 splide components and hide one or another with v-if. The problem with it is that the current displayed slide comes back to the first one when fullscreen is enabled/disabled and that it is not optimal

### Expected Behaviour

The correct width is applied to the splide component

**Comment by NaotoshiFujita** [comment]
Seems to be resolved.
https://github.com/Splidejs/splide/issues/683
