### ISSUE TITLE
Three dots appear in splide__list after update to 0.6.3

### ISSUE THREAD

**Issue by frankykubo** [Splidejs/vue-splide#65]
### Checks

- [x] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Vue Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.3

### Description

I updated from version 0.5.18 to 0.6.3. When I pick the carousel with mouseclick, pull it to side a bit and then release, after the track come back to its normal position. three dots with class splide__sr appear. This did not happen in previous version. Video is attached below, I cannot provide reproduction.

Carousel settings:
```ts
type: 'slide',
  rewind: false,
  waitForTransition: false,
  width: '100%',
  perMove: 1,
  speed: 700,
  pagination: false,
  arrowPath: 'M30.3,18.9L11.8,0.5c-0.6-0.6-1.6-0.6-2.2,0C9,1.1,9,2,9.7,2.6L27.1,20L9.7,37.4C9,38,9,38.9,9.7,39.5 c0.3,0.3,0.7,0.5,1.1,0.5c0.4,0,0.8-0.2,1.1-0.5l18.5-18.4c0.3-0.3,0.5-0.7,0.5-1.1C30.8,19.6,30.6,19.2,30.3,18.9z',
  breakpoints: {
    7000: {
      perPage: 6,
      gap: '30px',
    },
    1900: {
      perPage: 5,
      gap: '25px',
    },
    1400: {
      perPage: 4,
      gap: '20px',
    },
    1279: {
      perPage: 4,
      gap: '15px',
    },
    1024: {
      perPage: 3,
      gap: '10px',
    },
    768: {
      perPage: 2,
      gap: '10px',
    },
    640: {
      perPage: 1,
    },
```

https://user-images.githubusercontent.com/50501921/162427338-5d21b6c9-a605-4c9c-81fc-5411d7e99daa.mp4

### Steps to Reproduce

1. Install v0.6.3 of vue-splide
2. Pick and pull carousel to the side, then release and wait for animation to end
3. Three dots appear

### Expected Behaviour

Three dots not appearing.

**Comment by NaotoshiFujita** [comment]
You need to update CSS too.

**Comment by frankykubo** [comment]
Sorry, I did not thought about that. My bad. Thank you.
