### ISSUE TITLE
LazyLoad support ?

### ISSUE THREAD

**Issue by ThomasTraineau** [Splidejs/vue-splide#68]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Vue Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.5.18 (vue-splide)

### Description

As written in the documentation, I used the `data-splide-lazy="path-to-image"` with the `lazyLoad: true` option. The 2 first images are loaded but not the next ones.

The problem is that when scrolling to the next ones, a loading animation is displayed but the next images are not loaded and no request is made in the network tab.

Another problem I encountered, I couldn't catch the `lazyload:loaded` event with `@lazyload:loaded`

### Steps to Reproduce

Add multiple images to a vue-splide component with lazy-load enabled

### Expected Behaviour

Lazy loads the images

**Comment by NaotoshiFujita** [comment]
It's working as I expected:
https://codesandbox.io/s/lazyload-p8isup

**Comment by ThomasTraineau** [comment]
Thanks for the example ! But what about the `lazyload:loaded` event ?

**Comment by NaotoshiFujita** [comment]
The splide prefix is missing.
https://splidejs.com/integration/vue-splide/#events

**Comment by ThomasTraineau** [comment]
thanks again !
