### ISSUE TITLE
Change direction on breakpoints 

### ISSUE THREAD

**Issue by CoolS2** [Splidejs/vue-splide#7]
It would be great to change the direction of the slider for the mobile version

Example:

`sliderOptions: {
                    direction: 'ttb',
                    height   : '425px',
                    width   : '80px',
                    breakpoints: {
                        '768': {
                            direction: 'ltr',
                            width   : '100%',
                            height   : '80px',
                        },
                    }
                }`

**Comment by NaotoshiFujita** [comment]
Mmm, but is that okay the direction is suddenly changed by just resizing a window? I think the UX is not good.

I recommend switch 2 sliders, detecting devices:
```vue
<div v-if="isMobile()">
  <div id="right-slider"></div>
</div>
<div v-else>
  <div id="left-slider"></div>
</div>
```
