### ISSUE TITLE
splide vue violate Content Security Policy

### ISSUE THREAD

**Issue by vobar** [Splidejs/vue-splide#70]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Vue Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

^0.6.7

### Description

![image](https://user-images.githubusercontent.com/4314201/180173091-522afe9e-bd37-4a7d-93f3-fd327349cdd1.png)

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

Inline Style Attribute violate csp

### Steps to Reproduce

1. activate csp headers
(in my case: content-security-policy: style-src 'self';)

### Expected Behaviour

no error messages in console and completely support Content Security Policy in on of the best slider that can i seen

**Comment by NaotoshiFujita** [comment]
By design. Splide requires inline styles.
I used to try to remove them, but it leads terrible performance issue.
