### ISSUE TITLE
SplideTrack not exported

### ISSUE THREAD

**Issue by joshwcorbett** [Splidejs/vue-splide#72]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Vue Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.6.7

### Description

When attempting to import the `SplideTrack` component from `@splidejs/vue-splide` it states that it is not exported.

Simply using `SplideTrack` without importing results in wrapping the slides into one slide (of course).

### Steps to Reproduce

1. Within a vue project, try to use the `SplideTrack` component

### Expected Behaviour

According to the docs, there should exist the ability to use `SplideTrack` when we want to be more explicit about the structure and styling of a slider, but this component does not seem to be usable at all.

**Comment by NaotoshiFujita** [comment]
I confirmed it's available:
https://codesandbox.io/s/72-kcq6jk?file=/src/components/TrackExample.vue

**Comment by Ecpii** [comment]
Hello! Sorry for posting on an old issue, but I stumbled across this when trying out Splide for the first time on my Vue project. Following the [Vue tutorial](https://splidejs.com/integration/vue-splide/) and installing Splide via `app.use(VueSplide)`, I was indeed unable to use the `SplideTrack` component, with this warning in the console:
```
App.vue:2 [Vue warn]: Failed to resolve component: SplideTrack
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>
```
Here are the files I used:
**main.js**
```js
import './assets/main.css'

import { createApp } from 'vue'
import App from './App.vue'
import VueSplide from '@splidejs/vue-splide'

const app = createApp(App)
app.use(VueSplide)
app.mount('#app')
```
**App.vue**
```vue
<script setup>
// Default theme
import '@splidejs/vue-splide/css'
</script>

<template>
  <Splide :has-track="false">
    <SplideTrack>
      <SplideSlide>slide 1</SplideSlide>
      <SplideSlide>slide 2</SplideSlide>
      <SplideSlide>slide 3</SplideSlide>
    </SplideTrack>
  </Splide>
</template>
```
Output:
![image](https://github.com/user-attachments/assets/2111e64d-869e-46a4-bea4-c220c8e906a1)

**Comment by conradfuhrman** [comment]
A quick work around for this is to not import `VueSplide` in your main entry js file, but to use this import in your component:

`import { Splide, SplideSlide, SplideTrack } from '@splidejs/vue-splide';`

This does seem to be a bug when doing the VueSplide import and not the other method of importing.
