### ISSUE TITLE
The problem with determining the width

### ISSUE THREAD

**Issue by CoolS2** [Splidejs/vue-splide#8]
Periodically, there is a problem when a slider is created, the width is not calculated correctly, which is why the slider does not work correctly.

Perhaps this is due to the fact that the parent component is not fully loaded, and the slider will already enter a width calculation.

At the moment, the problem can be solved as follows:
`    methods:{
        onMounted(slider){
            setTimeout(function () {
                slider.refresh();
            },1500)
        }
    },`

![slider](https://user-images.githubusercontent.com/12847785/87014356-b315cf80-c1d4-11ea-8fe4-6d6dcfe6ef0f.jpg)

**Comment by NaotoshiFujita** [comment]
Basically, the parent element width determines the slider width, and it should do.

What changes the width of the parent element after DOM load? Images?

**Comment by CoolS2** [comment]
The parent only has a slider with pictures, in the parameters it is indicated to display 4 items in the slider, but 1 and a half is displayed, after **slider.refresh()** calculate correctly

**Comment by NaotoshiFujita** [comment]
If this is a common problem, it should happen to my [examples](https://splidejs.github.io/vue-splide/) too, but I've never seen this kind of things.

1. Do you use the latest version?
1. Does resizing a window fix the problem when it happens? The slider calculates dimensions again every time when a window is resized.
1. What if setting style `width: 100%` to the parent element?

I want to know what changes the width of the parent element. Each slide width is determined by `"width of a slider" / 4`. And the "width of a slider" comes from the parent width unless you specify a `width` option. That means something changes the width of the parent element before/after load.

**Comment by CoolS2** [comment]
1. Yes
2. Yes, resizing fix the problem
3. Parent has width: 100%; 

Maybe this problem is due to the fact that I'm using a vue router with lazy load components

**Comment by NaotoshiFujita** [comment]
Is that possible to disable the lazy load and check the slider again?

**Comment by vivekKodira** [comment]
Also faced something similar. In my case the array was initially empty. Splide's calculations were going haywire. Adding a v-if and delaying the rendering of splide to after the array had some elements was what fixed it.
